
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Age of Discontuinity, The','Drucker, Peter','economics','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Age of Wrath, The','Eraly, Abraham','history','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Aghal Paghal','Deshpande, P L','nonfiction','Mauj');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Ahe Manohar Tari','Deshpande, Sunita','nonfiction','Mauj');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('All the President''s Men','Woodward, Bob','history','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Amulet of Samarkand, The','Stroud, Jonathan','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Analysis, Vol I','Tao, Terence','mathematics','HBA');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Angels & Demons','Brown, Dan','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Argumentative Indian, The','Sen, Amartya','nonfiction','Picador');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Artist and the Mathematician, The','Aczel, Amir','science','HighStakes');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Asami Asami','Deshpande, P L','fiction','Mauj');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Ashenden of The British Agent','Maugham, William S','fiction','Vintage');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Beautiful and the Damned, The','Deb, Siddhartha','nonfiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Beyond the Three Seas','Dalrymple, William','history','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Birth of a Theorem','Villani, Cedric','mathematics','Bodley Head');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Bookless in Baghdad','Tharoor, Shashi','nonfiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Brethren, The','Grisham, John','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Burning Bright','Steinbeck, John','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Catch 22','Heller, Joseph','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('City of Joy, The','Lapierre, Dominique','fiction','vikas');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Clash of Civilizations and Remaking of the World Order','Huntington, Samuel','history','Simon&Schuster');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Complete Mastermind, The','BBC','nonfiction','BBC');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Complete Sherlock Holmes, The - Vol I','Doyle, Arthur Conan','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Complete Sherlock Holmes, The - Vol II','Doyle, Arthur Conan','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Computer Vision, A Modern Approach','Forsyth, David','data_science','Pearson');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Crime and Punishment','Dostoevsky, Fyodor','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Data Mining Handbook','Nisbet, Robert','data_science','Apress');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Data Scientists at Work','Sebastian Gutierrez','data_science','Apress');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Data Smart','Foreman, John','data_science','Wiley');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Data Structures Using C & C++','Tanenbaum, Andrew','computer_science','Prentice Hall');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Doctor in the Nude','Gordon, Richard','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Down and Out in Paris & London','Orwell, George','nonfiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Drunkard''s Walk, The','Mlodinow, Leonard','science','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Dylan on Dylan','Dylan, Bob','nonfiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Econometric Analysis','Greene, W. H.','economics','Pearson');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Electric Universe','Bodanis, David','science','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('False Impressions','Archer, Jeffery','fiction','Pan');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Farewell to Arms, A','Hemingway, Ernest','fiction','Rupa');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Freakonomics','Dubner, Stephen','economics','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Free Will','Harris, Sam','philosophy','FreePress');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Freedom at Midnight','Lapierre, Dominique','history','vikas');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Fundamentals of Wavelets','Goswami, Jaideva','signal_processing','Wiley');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('God Created the Integers','Hawking, Stephen','mathematics','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Great Indian Novel, The','Tharoor, Shashi','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Great War for Civilization, The','Fisk, Robert','history','HarperCollins');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Gun Gayin Awadi','Deshpande, P L','nonfiction','Mauj');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Hidden Connections, The','Capra, Fritjof','science','HarperCollins');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('History of Western Philosophy','Russell, Bertrand','philosophy','Routledge');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('How to Think Like Sherlock Holmes','Konnikova, Maria','psychology','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Hunchback of Notre Dame, The','Hugo, Victor','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Idea of Justice, The','Sen, Amartya','nonfiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Identity & Violence','Sen, Amartya','philosophy','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Image Processing & Mathematical Morphology','Shih, Frank','signal_processing','CRC');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('In a Free State','Naipaul, V. S.','fiction','Rupa');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('India from Midnight to Milennium','Tharoor, Shashi','history','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Integration of the Indian States','Menon, V P','history','Orient Blackswan');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Introduction to Algorithms','Cormen, Thomas','computer_science','MIT Press');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Journal of a Novel','Steinbeck, John','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Jurassic Park','Crichton, Michael','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Last Lecture, The','Pausch, Randy','nonfiction','Hyperion');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Last Mughal, The','Dalrymple, William','history','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Learning OpenCV','Bradsky, Gary','data_science','O''Reilly');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Let Us C','Kanetkar, Yashwant','computer_science','Prentice Hall');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Machine Learning for Hackers','Conway, Drew','data_science','O''Reilly');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Making Software','Oram, Andy','computer_science','O''Reilly');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Manasa','Kale, V P','nonfiction','Mauj');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Maqta-e-Ghalib','Garg, Sanjay','fiction','Mauj');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Maugham''s Collected Short Stories, Vol 3','Maugham, William S','fiction','Vintage');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Moon is Down, The','Steinbeck, John','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Nature of Statistical Learning Theory, The','Vapnik, Vladimir','data_science','Springer');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('New Machiavelli, The','Wells, H. G.','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('New Markets & Other Essays','Drucker, Peter','economics','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('O Jerusalem!','Lapierre, Dominique','history','vikas');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('On Education','Russell, Bertrand','philosophy','Routledge');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Once There Was a War','Steinbeck, John','nonfiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('One','Bach, Richard','nonfiction','Dell');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Orientalism','Said, Edward','history','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Outsider, The','Camus, Albert','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Physics & Philosophy','Heisenberg, Werner','science','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Pillars of the Earth, The','Follett, Ken','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Principles of Communication Systems','Taub, Schilling','computer_science','TMH');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Prisoner of Birth, A','Archer, Jeffery','fiction','Pan');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Python for Data Analysis','McKinney, Wes','data_science','O''Reilly');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Radiowaril Bhashane & Shrutika','Deshpande, P L','nonfiction','Mauj');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Raisin in the Sun, A','Hansberry, Lorraine','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Rationality & Freedom','Sen, Amartya','economics','Springer');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Return of the Primitive','Rand, Ayn','philosophy','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Russian Journal, A','Steinbeck, John','nonfiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Scoop!','Nayar, Kuldip','history','HarperCollins');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Sea of Poppies','Ghosh, Amitav','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Signal and the Noise, The','Silver, Nate','data_science','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Slaughterhouse Five','Vonnegut, Kurt','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Social Choice & Welfare, Vol 39 No. 1','Various','economics','Springer');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Soft Computing & Intelligent Systems','Gupta, Madan','data_science','Elsevier');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Statistical Decision Theory''','Pratt, John','data_science','MIT Press');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Story of Philosophy, The','Durant, Will','philosophy','Pocket');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Structure & Interpretation of Computer Programs','Sussman, Gerald','computer_science','MIT Press');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Superfreakonomics','Dubner, Stephen','economics','HarperCollins');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Surely You''re Joking Mr Feynman','Feynman, Richard','science','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Tales of Mystery and Imagination','Poe, Edgar Allen','fiction','HarperCollins');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Tao of Physics, The','Capra, Fritjof','science','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Textbook of Economic Theory','Stonier, Alfred','economics','Pearson');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Theory of Everything, The','Hawking, Stephen','science','Jaico');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('To Sir With Love','Braithwaite','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Trial, The','Kafka, Frank','fiction','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Uncommon Wisdom','Capra, Fritjof','nonfiction','Fontana');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Veteran, The','Forsyth, Frederick','fiction','Transworld');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('We the Living','Rand, Ayn','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES (NULL,NULL,NULL,NULL);
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Wealth of Nations, The','Smith, Adam','economics','Random House');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Winter of Our Discontent, The','Steinbeck, John','fiction','Penguin');
INSERT INTO table_book(title,author,genre,publisher) VALUES ('Zen & The Art of Motorcycle Maintenance','Pirsig, Robert','philosophy','Vintage');
